apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: helloworld
  namespace: default
spec:
  selector:
    matchLabels:
      app: helloworld
  rules:
  - from:
    - source:
        requestPrincipals: ["*"]
